services:
  foxglove:
    build:
      context: ../..
      dockerfile: Dockerfile
    network_mode: host
    # image: husarion/foxglove-desktop:humble-2.0.1-20240319
    runtime: ${DOCKER_RUNTIME:-runc}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/udev/data/:/run/udev/data/
    devices:
      - /dev/input
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
      - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
      - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored

